# Name of your application. Used to uniquely configure containers.
service: uxauditapp

# Name of the container image.
image: zelusottomayor/uxauditapp

# Deploy to these servers.
servers:
  web:
    hosts:
      - 143.110.169.251
    options:
      memory: "2g"
      cpus: "1.0"
    labels:
      # Router: match your host on both :80 and :443 and enable TLS at the proxy
      traefik.http.routers.uxauditapp-web.rule: Host(`uxauditapp.zelusottomayor.com`)
      traefik.http.routers.uxauditapp-web.entrypoints: web,websecure
      traefik.http.routers.uxauditapp-web.tls: "true"

      # Service: Traefik talks HTTP to Puma on 3000 (no TLS to the app!)
      traefik.http.services.uxauditapp-web.loadbalancer.server.port: "3000"
      traefik.http.services.uxauditapp-web.loadbalancer.server.scheme: http
  workers:
    hosts:
      - 143.110.169.251
    cmd: bundle exec sidekiq
    options:
      memory: "2g"
      cpus: "1.0"

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
# Remove this section when using multiple web servers and ensure you terminate SSL at your load balancer.
#
# Note: If using Cloudflare, set encryption mode in SSL/TLS setting to "Full" to enable CF-to-app encryption.
proxy:
  host: uxauditapp.zelusottomayor.com
  ssl: true
  app_port: 3000
  healthcheck:
    path: /up
    interval: 3
    timeout: 3

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  username: zelusottomayor

  # Always use an access token rather than real password (pulled from .kamal/secrets).
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64
  # Pass in additional build args needed for your Dockerfile.
  # args:
  #   RUBY_VERSION: <%= ENV["RBENV_VERSION"] || ENV["rvm_ruby_string"] || "#{RUBY_ENGINE}-#{RUBY_ENGINE_VERSION}" %>

# Inject ENV variables into containers (secrets come from .kamal/secrets).
#
env:
  clear:
    RAILS_ENV: production
    REDIS_URL: redis://143.110.169.251:6380/0
    RAILS_MAX_THREADS: 8
    WEB_CONCURRENCY: 2
  secret:
    - RAILS_MASTER_KEY
    - OPENAI_API_KEY
    - DATABASE_URL

# Use a persistent storage volume for all containers.
#
volumes:
  - "/mnt/volume-lon1-01/uxauditapp:/rails/storage"
  - "/mnt/volume-lon1-01/uxauditapp-tmp:/rails/tmp"

# Configure rolling deploys by setting a wait time between batches of restarts.
#
boot:
  limit: 120 # seconds to wait for container to be ready

# Use accessory services (secrets come from .kamal/secrets).
#
accessories:
  redis:
    image: redis:7
    host: 143.110.169.251
    port: 6380
    cmd: redis-server --port 6380
    directories:
      - /mnt/volume-lon1-01/uxauditapp-redis:/data
    options:
      memory: "1g"
      cpus: "0.5"
